// USERS ACTIONS
export const USERS_LOADED = "USERS_LOADED";
export const USERS_LOADING = "USERS_LOADING";
export const GET_USERS = "UPDATE_USER";
export const CREATE_USER = "CREATE_USER";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAIL = "GET_USERS_FAIL";
export const CREATE_USER_FAIL = "CREATE_USER_FAIL";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const SET_PAGE = "SET_PAGE";

//ERROR ACTIONS
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

// CONFIG ACTIONS
export const RESET_SESSION = "RESET_SESSION";
