// USER
export const UPDATE_USER = 'UPDATE_USER';

// AUTH
export const USER_LOADED = 'USER_LOADED';
export const USER_LOADING = 'USER_LOADING';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const RESET_SESSION = 'RESET_SESSION';
export const UPDATE_AUTH = 'UPDATE_AUTH';

//ERROR ACTIONS
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

// CONFIG REDUCER
export const SET_TOP_BAR = 'SET_TOP_BAR';
